// Opt-in protocol client checks. Run against the disposable Paper 1.21.8 test world.
// Dependency: npm install --prefix .runtime/bot mineflayer@4.39.0
const assert = require('node:assert/strict');
const { once } = require('node:events');
const path = require('node:path');
const mineflayer = require(path.join(__dirname, '../.runtime/bot/node_modules/mineflayer'));
const bot = mineflayer.createBot({ host: '127.0.0.1', port: 25587, username: 'EasyTest', version: '1.21.8', auth: 'offline' });
let passes = 0;
const messages = [];
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
const count = name => bot.inventory.items().filter(item => item.name === name).reduce((n, item) => n + item.count, 0);
const check = (name, valid) => { assert.ok(valid, name); console.log('PASS', ++passes, name); };
bot.on('error', error => console.error(error));
bot.on('kicked', reason => console.error('KICKED', reason));
bot.on('messagestr', text => { messages.push(text); console.log('CHAT', text); });
const command = async text => { bot.chat(text); await pause(400); };
async function open(commandText) {
  const opened = once(bot, 'windowOpen', { signal: AbortSignal.timeout(5000) });
  bot.chat(commandText); await opened; return bot.currentWindow;
}
bot.once('spawn', async () => {
  console.log('BOT READY: grant op EasyTest in this isolated server console. Tests start in 12 seconds.');
  await pause(12000);
  try {
    await command('/clear');
    await command('/es player health 20');
    await command('/es item give diamond 3');
    check('item delivery', count('diamond') === 3);
    await open('/es menu main');
    check('studio has 54 slots', bot.currentWindow.inventoryStart === 54);
    const before = count('diamond');
    await bot.clickWindow(15, 0, 1); await pause(400);
    check('menu shift-click cannot steal icon', count('writable_book') === 0 && count('diamond') === before);
    if (bot.currentWindow) bot.closeWindow(bot.currentWindow);
    await command('/es kit save client_kit');
    await command('/clear'); await command('/es kit apply client_kit');
    check('kit restores three diamonds', count('diamond') === 3);
    await command('/es take snapshot'); await command('/es player health 6');
    check('player health control', bot.health === 6);
    await command('/es player freeze on');
    await command('/es take reset'); await command('/es take discard');
    check('take restores health', bot.health === 20);
    await command('/es inventory save');
    await open('/es menu kits'); check('saved kit listed', bot.currentWindow.slots.some(i => i && i.name === 'chest'));
    await bot.clickWindow(10, 1, 0); await pause(400);
    check('kit editor opens', bot.currentWindow && bot.currentWindow.slots[47]?.name === 'emerald');
    const bottom = bot.currentWindow.slots.findIndex((i, n) => n >= 54 && i?.name === 'diamond');
    await bot.clickWindow(bottom, 0, 0); await pause(150);
    await bot.clickWindow(1, 0, 0); await pause(150);
    check('kit editor does not consume player items', count('diamond') === 3);
    await bot.clickWindow(47, 0, 0); await pause(400);
    if (bot.currentWindow) bot.closeWindow(bot.currentWindow);
    await command('/clear'); await command('/es kit apply client_kit');
    check('ghost slot saved as intentional kit copy', count('diamond') === 6);
    await command('/es kit delete client_kit');
    await command('/es actor create client_actor ZOMBIE');
    const created = messages.findLast(text => text.includes("Created actor 'client_actor':"));
    const generatedName = created?.match(/name=([A-Za-z0-9_]+);/)?.[1];
    check('mob receives generated name', generatedName && generatedName !== 'client_actor' && created.includes('skin=mob appearance'));
    await open('/es actor gui client_actor appearance');
    check('actor identity controls present in schema-2 GUI', bot.currentWindow.slots[31]?.name === 'ender_eye' && bot.currentWindow.slots[11]?.name === 'name_tag');
    await bot.clickWindow(0, 0, 0); await pause(400);
    let messageStart = messages.length;
    await bot.clickWindow(22, 0, 0); await pause(400);
    check('GUI identity button reports stable ID and generated name', messages.slice(messageStart).some(text => text.includes("actor 'client_actor': name=" + generatedName)));
    messageStart = messages.length;
    await bot.clickWindow(1, 0, 0); await pause(400);
    await bot.clickWindow(31, 0, 0); await pause(400);
    const rerolled = messages.slice(messageStart).find(text => text.includes("Randomized actor 'client_actor':"));
    check('GUI randomization changes mob name and retains ID', rerolled && !rerolled.includes('name=' + generatedName + ';') && rerolled.includes('type=ZOMBIE'));
    if (bot.currentWindow) bot.closeWindow(bot.currentWindow);
    await command('/es record startall client_sync');
    await pause(600); await command('/es record stopall');
    await command('/es record playgroup on on client_sync_easytest=client_actor');
    await command('/es status');
    check('synchronized capture and looping reverse playback', messages.some(text => text.includes("Saved movement 'client_sync_easytest'")) && /active jobs=2\b/.test(messages.at(-1)));
    await command('/es record stopplay client_actor');
    await command('/es record delete client_sync_easytest');
    await command('/es actor delete client_actor');
    await command('/setblock 20 -60 20 stone');
    await command('/tp 20.5 -59 20.5');
    await command('/es region pos1'); await command('/es region pos2');
    await command('/tp 18.5 -60 20.5');
    await command('/setblock 20 -59 20 chest');
    await command('/item replace block 20 -59 20 container.0 with diamond 5');
    await command('/es region save client_region');
    await command('/setblock 20 -59 20 air');
    await command('/es region restore client_region');
    const restored = bot.blockAt(new (require(path.join(__dirname, '../.runtime/bot/node_modules/vec3')).Vec3)(20, -59, 20));
    check('region restores block data', restored?.name === 'chest');
    const chest = await bot.openContainer(restored);
    check('region restores container snapshot', chest.containerItems().some(item => item.name === 'diamond' && item.count === 5));
    chest.close(); await pause(200);
    await command('/es region delete client_region');
    await command('/setblock 20 -59 20 air'); await command('/setblock 20 -60 20 air');
    await command('/es status');
    console.log(`CLIENT TESTS PASSED: ${passes}`);
    bot.quit(); process.exitCode = 0;
  } catch (error) { console.error('CLIENT TESTS FAILED', error); bot.quit(); process.exitCode = 1; }
});
setTimeout(() => { if (!bot._client.ended) { console.error('Client test timeout'); bot.quit(); process.exitCode = 1; } }, 90000).unref();
